modLoader="javafml"
loaderVersion="[27,)" 
issueTrackerURL="https://github.com/kevin68/The-Spotlight-Mod/issues" 

[[mods]] 
modId="thespotlightmod"
version="${file.jarVersion}"
displayName="The SpotLight Mod"
updateJSONURL="http://dl.mcnanotech.fr/kevin_68/TSM/version.json"
displayURL="https://minecraft.curseforge.com/projects/the-spotlight-mod"
logoFile="/assets/thespotlightmod/banner.png"
credits="With the contribution of robin4002"
authors="kevin_68"
description='''
The Spotlight Mod adds a block similar to the beacon but with only a aesthetic purpose and with a lot of customizable features.
'''

[[dependencies.thespotlightmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"